---
- name: Check possible VirtualBox source uninstall script locations
  ansible.builtin.stat:
    path: "{{ item }}"
  register: virtualbox_uninstall_script_stats
  loop:
    - /usr/lib/virtualbox/uninstall.sh
    - /opt/VirtualBox/uninstall.sh
  loop_control:
    label: "{{ item }}"

- name: Determine VirtualBox source uninstall script path
  ansible.builtin.set_fact:
    virtualbox_uninstall_script_path: >-
      {{ (virtualbox_uninstall_script_stats.results
          | selectattr('stat.exists', 'true')
          | map(attribute='item') | list | first) | default('', true) }}

- name: Wait for any running VirtualBox instance to stop
  ansible.builtin.include_tasks: noauto_wait_for_virtualbox_stopped.yml

- name: Uninstall VirtualBox from source
  ansible.builtin.command:
    cmd: "{{ virtualbox_uninstall_script_path }}"
  when: virtualbox_uninstall_script_path != ""
  become: true
  changed_when: true
