---
- name: Install VirtualBox from source
  block:
    - name: Import installed virtualbox version check
      ansible.builtin.include_tasks: noauto_check_installed_version.yml
      when: virtualbox_installed_version is not defined

    - name: Force install if the version numbers do not match
      ansible.builtin.set_fact:
        virtualbox_force_install: true
      when:
        - virtualbox_installed_version is defined
        - virtualbox_installed_version != virtualbox_version

    - name: Install virtualbox from source
      when: virtualbox_installed_version is not defined or virtualbox_force_install
      block:
        - name: Uninstall current virtualbox installation
          ansible.builtin.include_tasks: noauto_uninstall.yml
          when: virtualbox_installed_version is defined and virtualbox_installed_version != ""

        - name: Download virtualbox
          ansible.builtin.get_url:
            url: "{{ virtualbox_download_url }}"
            dest: "{{ virtualbox_download_dir }}/{{ virtualbox_package_name }}"
            mode: "0600"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Wait for any running VirtualBox instance to stop
          ansible.builtin.include_tasks: noauto_wait_for_virtualbox_stopped.yml

        - name: Install OS-specifically from source
          ansible.builtin.include_tasks: "{{ task_file }}"
          with_first_found:
            - "{{ role_path }}/tasks/noauto_install_source_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ role_path }}/tasks/noauto_install_source_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ role_path }}/tasks/noauto_install_source_{{ ansible_distribution }}.yml"
            - "{{ role_path }}/tasks/noauto_install_source_{{ ansible_os_family }}.yml"
            - "{{ role_path }}/tasks/noauto_install_source_{{ ansible_lsb.id }}.yml"
          loop_control:
            loop_var: task_file

        - name: Remove downloaded package
          ansible.builtin.file:
            path: "{{ virtualbox_download_dir }}/{{ virtualbox_package_name }}"
            state: absent
