---
- name: Install virtualbox OS-specifically via package
  ansible.builtin.include_tasks: "{{ task_file }}"
  with_first_found:
    - "noauto_install_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "noauto_install_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "noauto_install_{{ ansible_distribution }}.yml"
    - "noauto_install_{{ ansible_os_family }}.yml"
    - "noauto_install_{{ ansible_lsb.id }}.yml"
  loop_control:
    loop_var: task_file
