---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Add virtualbox apt key and repository
  block:
    - name: Ensure directory exists for /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
      become: true

    - name: Download Oracle VirtualBox repository key
      ansible.builtin.get_url:
        url: "{{ virtualbox_repository_gpg_key }}"
        dest: /etc/apt/keyrings/virtualbox.asc
        mode: "0644"
        force: false
        checksum: "{{ virtualbox_repository_gpg_key_checksum | default(omit) }}"
      failed_when:
        - virtualbox_key_download.failed
        - not virtualbox_repository_allow_key_error
        - virtualbox_key_download.status_code | default(0) not in [304, 200]
      register: virtualbox_key_download
      become: true

    - name: Add virtualbox repository
      ansible.builtin.apt_repository:
        repo: "{{ virtualbox_repository_url }}"
        state: present
        filename: "{{ virtualbox_repository_filename }}"
        update_cache: true
      become: true

- name: Ensure virtualbox dependencies are installed
  ansible.builtin.apt:
    name: "{{ package }}"
    state: present
  loop: "{{ virtualbox_dep_pkgs }}"
  loop_control:
    loop_var: package
  become: true
