---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Install virtualbox dependencies via apt
  when: virtualbox_distro_pkgs is defined and virtualbox_distro_pkgs | length > 0
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Get virtualbox version from package manager
      ansible.builtin.command:
        cmd: "apt-cache policy {{ virtualbox_distro_pkgs[0] }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: virtualbox_pkg_mgr_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        virtualbox_pkg_mgr_version: "{{ (virtualbox_pkg_mgr_version_cmd.stdout | regex_search('Candidate:\\ ([\\d\\.]+)', '\\1', multiline=True))[0] }}"

    - name: Debug virtualbox version from package manager
      ansible.builtin.debug:
        var: virtualbox_pkg_mgr_version
